
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uip-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uip-admin
  template:
    metadata:
      labels:
        app: uip-admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
