
version: "3.9"
services:
  admin:
    build: .
    ports:
      - "7000:7000"
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@db:5432/uip_admin
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uip_admin
    ports:
      - "5432:5432"
